# Generated by Django 3.0.5 on 2020-04-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200416_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('FAMILY_RELATIONSHIPS', 'Family Relationships'), ('ROMANTIC_RELATIONSHIPS', 'Romantic Relationships'), ('WORKPLACE_RELATIONSHIPS', 'Workplace Relationships'), ('COMPLICATED_RELATIONSHIPS', 'Complicated Relationships'), ('SACRED_RELATIONSHIPS', 'Sacred Relationships'), ('FORBIDDEN_RELATIONSHIPS', 'Forbidden Relationships'), ('EXTENDED_RELATIONSHIPS', 'Extended Relationships'), ('FRIENDS_RELATIONSHIPS', 'Friends Relationships'), ('OTHER_RELATIONSHIPS', 'Other Relationships')], default='FAMILY_RELATIONSHIPS', max_length=100, null=True),
        ),
    ]
